### ISSUE TITLE
Issue connecting after using kill script

### ISSUE THREAD

**Issue by daponte-ips** [SixArm/kill-palo-alto-networks-global-protect#1] opened 2019-12-16 15:08 UTC
Thanks for this, it's a great tool. One issue I'm experiencing is that after a while of using the kill script, eventually Global Protect stops connecting to our VPN server. The only thing that resolves it is reinstalling the client. It's not a huge problem, but a little inconvenient. Any ideas on how to mitigate this?

**Comment by joelparkerhenderson** [comment] 2019-12-18 08:30
You're welcome, and thanks for being so nice!

One idea to mitigate that is first be sure the processes are all dead, really dead, not just frozen or a zombie or some such. I added some bulletproofing code for you just now. 

Can you try this new version, at your convenience, and let me know if it helps or not?

**Comment by daponte-ips** [comment] 2020-01-10 16:32
Hey there. Happy New Year! I was able to test this again for the first time since before the holidays, and unfortunately it's a no-go. I wonder if the unload script is taking something out of memory that Global Protect is expecting to always be running in the background.

It's pretty easy to reproduce:

1. Connect to VPN via Global Protect
2. Run the kill script, here's the terminal output
>  % ~/kill-global-protect.sh
/Library/LaunchAgents/com.paloaltonetworks.gp.pangpa.plist: Operation now in progress
/Library/LaunchAgents/com.paloaltonetworks.gp.pangps.plist: Operation now in progress
Password:
No matching processes were found
No matching processes were found
No matching processes were found
No matching processes were found

3. Launch Global Protect and attempt to reconnect
4. You're now stuck on a "Connecting..." screen
> <img width="254" alt="Screen Shot 2020-01-10 at 11 31 27 AM" src="https://user-images.githubusercontent.com/23171147/72169298-d2a27b80-339c-11ea-9bb4-270552cb7c52.png">

The only thing that removes this state is reinstalling the VPN client.

I'm on macOS Catalina version 10.15.2 (19C57)

**Comment by daponte-ips** [comment] 2020-01-10 18:39
Found the issue. It turned out to be pretty simple. The GlobalProtect process is dependent upon the PanGPS process, so you just have to reload the PanGPS process alongside the GP one. Since these process are loaded via `launchctl`, it made sense to add the capability of launching GP to the same script that you had, so that we have one script that can do both.

I forked off your repo and added the changes. You can see them in the pull request here: #2

**Comment by joelparkerhenderson** [comment] 2020-01-12 22:30
Yes you’re right, the kill script unloads PanGPS, and any relaunch of Global Protect requires a reload of PanGPS, such as by running launchctl. I have a separate two-line script that does the start of PanGPS, and I’ll upload that today.

The kill script purpose is to kill, not start/restart/reload/etc. I’ll take a look at your PR today too. Thanks!

**Comment by daponte-ips** [comment] 2020-01-13 14:55
Ok no worries, if you'd rather not merge the changes I can just keep the fork separate or even make a separate project on Github.

**Comment by joelparkerhenderson** [comment] 2020-01-14 04:25
Here's the start script, which is as you expect: https://github.com/SixArm/start-palo-alto-networks-global-protect

Yes I like your idea of a separate fork and/or separate project. Your approach is better for a real tool, with command line options, error piping, help messages, etc. My approach is deliberately just quick and dirty. I believe most users will prefer your approach. Thanks!

**Comment by joelparkerhenderson** [comment] 2020-01-19 23:22
Closing because the issue is solved and Danny has the code for a new repo.

**Closed as completed by joelparkerhenderson** 2020-01-19 23:22 UTC
